title: "ESPGeiger"
description: Create your IoT connected Geiger Counter
color_scheme: nil

remote_theme: just-the-docs/just-the-docs

permalink: pretty
exclude: []

avatar: /img/ESPGeiger.svg

aux_links:
  "ESPGeiger on GitHub":
    - "//github.com/steadramon/ESPGeiger"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

callouts:
  highlight:
    color: yellow
