title: "ESPGeiger"
description: A Jekyll theme for documentation
color_scheme: nil

remote_theme: just-the-docs/just-the-docs

permalink: pretty
exclude: []

aux_links:
  "ESPGeiger on GitHub":
    - "//github.com/steadramon/ESPGeiger"

