name: Release

on:
  release:
    types: [published]

jobs:
  build-upload:
    runs-on: ubuntu-latest
    name: Build and upload Assets to Release
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Set version tag from git
        run: sed -i "s/RELEASE_VERSION \"devel\"/RELEASE_VERSION \"${GITHUB_REF#refs/tags/}\"/g" ESPGeiger/src/Status.h
      - name: Run PlatformIO
        run: platformio run
      - name: Prepare Release Assets
        run: |
          sudo apt install rename
          bash ./scripts/prepare_deploy.sh ${GITHUB_REF#refs/tags/}
      - name: Get upload url
        id: release-id
        run: |
          RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          echo "release_upload_url=https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets{?name,label}" >> $GITHUB_ENV
      - name: Upload Release Assets
        uses: bgpat/release-asset-action@03b0c30db1c4031ce3474740b0e4275cd7e126a3
        with:
          pattern: "toDeploy/*"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ env.release_upload_url }}
          allow-overwrite: true